site_name: MyTool Documentation
site_description: A self-study introduction to Dyalog APL
docs_dir: docs/
repo_name: 'RikedyP/MyTool'
repo_url: 'https://github.com/rikedyp/MyTool'
theme:
  name: material
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
plugins:
  - search
  - awesome-pages
  - section-index
extra_css:
  - style/main.css