site_name: MyTool Documentation
site_description: An example GitHub repository
docs_dir: docs/
repo_name: 'RikedyP/MyTool'
repo_url: 'https://github.com/rikedyp/MyTool'
theme:
  name: material
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.instant
markdown_extensions:
  - admonition
plugins:
  - search
  - awesome-pages
  - section-index
extra_css:
  - style/main.css